// src/modules/moduleBank.js
export const moduleBank = [
  {
    id: "fractions",
    title: "Fractions Mastery",
    age: "11–15",
    emoji: "🍕",
    description: "Add/subtract/multiply/divide fractions in real-life stories.",
    geminiTopic: "fractions",
  },
  {
    id: "algebra_basics",
    title: "Algebra Basics",
    age: "11–15",
    emoji: "🧩",
    description: "Simplify expressions, substitute values, and evaluate.",
    geminiTopic: "algebra basics",
  },
  {
    id: "linear_equations",
    title: "Linear Equations",
    age: "11–15",
    emoji: "📈",
    description: "Solve ax + b = c using step-by-step reasoning.",
    geminiTopic: "linear equations",
  },
  {
    id: "inequalities",
    title: "Inequalities",
    age: "11–15",
    emoji: "⚖️",
    description: "Solve inequalities and interpret solutions.",
    geminiTopic: "inequalities",
  },
  {
    id: "ratio_proportion",
    title: "Ratio & Proportion",
    age: "11–15",
    emoji: "🧪",
    description: "Scaling, recipes, maps, unitary method.",
    geminiTopic: "ratios and proportions",
  },
  {
    id: "percentages",
    title: "Percentages",
    age: "11–15",
    emoji: "💸",
    description: "Discounts, profit/loss, percentage change.",
    geminiTopic: "percentages",
  },
  {
    id: "exponents",
    title: "Exponents & Powers",
    age: "11–15",
    emoji: "⚡",
    description: "Powers, rules of indices, basic scientific notation.",
    geminiTopic: "exponents and powers",
  },
  {
    id: "geometry",
    title: "Geometry",
    age: "11–15",
    emoji: "📐",
    description: "Area, perimeter, angles, triangles.",
    geminiTopic: "geometry",
  },
  {
    id: "statistics",
    title: "Statistics",
    age: "11–15",
    emoji: "📊",
    description: "Mean/median/mode, simple probability.",
    geminiTopic: "statistics and probability",
  },
];